### PR TITLE
feat: Add a basic make test

### PR DESCRIPTION
**Pull request by tumido**
In order to better see the validation performed via https://github.com/thoth-station/helm-charts/pull/34 I'm adding a simple `make test` rule.

```bash
$ make test

Queuing import pipelines... Done
Waiting for pipelines to finish execution....... Done
Results:
NAME                   DESCRIPTION                                 PHASE    VISIBILITY   MESSAGES
Image does not exist   This image is expected to FAIL validation   Failed   false        [{"severity":"error","message":"Unable to pull image"}]

Thoth Station miminal Python 3.8   This image is expected to PASS validation   Succeeded   true
Debian based miminal Python 3.8    This image is expected to PASS validation   Succeeded   true
Thoth Station miminal Python 3.6   This image is expected to FAIL validation   Failed      false        [{"severity":"error","message":"Python version does not meet minimal required version ('3.8.0')"}]
```

### CODE REVIEW

**Review by oindrillac — COMMENTED** [review]
Thanks @tumido! 
Tested. All test cases work as expected, except these 2:

```
Thoth Station miminal Python 3.8   This image is expected to PASS validation   Failed
                                   false
                                   [{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]
```
```
Thoth Station miminal Python 3.8   This image is expected to PASS validation   Failed
                                   false
                                   [{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]
```

**Comment by oindrillac** [comment]
The complete output:

```bash
% make test 
-n Queuing import pipelines...
 Done
-n Waiting for pipelines to finish execution...
 Done
Results:
NAME                   DESCRIPTION                                 PHASE   VISIBILITY   MESSAGES
Image does not exist   This image is expected to FAIL validation   Failed
                       false
                       [{"severity":"error","message":"Unable to pull image"}]

Image does not exist   This image is expected to FAIL validation   Failed
                       false
                       [{"severity":"error","message":"Unable to pull image"}]

Thoth Station miminal Python 3.8   This image is expected to PASS validation   Failed
                                   false
                                   [{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]

Thoth Station miminal Python 3.6   This image is expected to FAIL validation   Failed
                                   false
                                   [{"severity":"error","message":"Python version does not meet minimal required version ('3.8.0')"}]

Thoth Station miminal Python 3.6   This image is expected to FAIL validation   Failed
                                   false
                                   [{"severity":"error","message":"Python version does not meet minimal required version ('3.8.0')"},{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]

Thoth Station miminal Python 3.6   This image is expected to FAIL validation   Failed
                                   false
                                   [{"severity":"error","message":"Python version does not meet minimal required version ('3.8.0')"},{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]

Debian based miminal Python 3.8    This image is expected to PASS validation   Succeeded
                                   true
                                   
Debian based miminal Python 3.8    This image is expected to PASS validation   Succeeded
                                   true
                                   
Thoth Station miminal Python 3.8   This image is expected to PASS validation   Failed
                                   false
                                   [{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]

```

**Comment by tumido** [comment]
Huh, yeah.. in some cases it's flaking for me as well. The same image can both pass and fail validation:

```
NAME                               DESCRIPTION                                 PHASE       VISIBILITY   MESSAGES
Thoth Station miminal Python 3.8   This image is expected to PASS validation   Succeeded   true         
Thoth Station miminal Python 3.8   This image is expected to PASS validation   Failed      false        [{"severity":"error","message":"start-singleuser.sh script took too long to call 'jupyter labhub'"}]
```

I think it's related to the `timeout 30` call - when the cluster is under significant CPU load this can take longer. Which is weird. Let's extend the timeout to 60sec. I think timeout must be present in case the script is executing something else than jupyter, so we don't allow it to run forever.

**Review by oindrillac — APPROVED** [review]
/lgtm

**Pull request merged**
