### PR TITLE
added OS-Climate image to test

### PR DESCRIPTION
**Pull request by oindrillac**
## Related Issues and Dependencies
#34 

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by oindrillac** [comment]
cc @tumido

**Comment by codificat** [comment]
/lgtm

<details>

<summary>quick local test output:</summary>

```
$ tkn pipeline start byon-import-jupyterhub-image \
> -w name=data,volumeClaimTemplateFile=manifests/overlays/dev/pvc.yaml \
> -p url=quay.io/os-climate/aicoe-osc-demo:latest \
> -p name="OS-Climate image with Pytorch" \
> -p desc="This image is expected to PASS validation"
PipelineRun started: byon-import-jupyterhub-image-run-72f6n

$ tkn pipelinerun logs byon-import-jupyterhub-image-run-72f6n -f
[create-imagestream : oc] Creating image stream:
[create-imagestream : oc]   Name:       byon-import-jupyterhub-image-run-72f6n
[create-imagestream : oc]   Namespace:  byon
[create-imagestream : oc] 
[create-imagestream : oc]   Image name:        OS-Climate image with Pytorch
[create-imagestream : oc]   Image description: This image is expected to PASS validation
[create-imagestream : oc]   Image URL:         quay.io/os-climate/aicoe-osc-demo:latest
[create-imagestream : oc] 
[create-imagestream : oc]   Phase:             Validating
[create-imagestream : oc]   Message:           ''
[create-imagestream : oc]   Visibility:        false
[create-imagestream : oc]   Origin:            Admin
[create-imagestream : oc] 
[create-imagestream : oc] imagestream.image.openshift.io/byon-import-jupyterhub-image-run-72f6n created

[setup : setup] Creating output files... DONE
[setup : setup] Verifying image is pull-able... DONE

[validate : get-package-versions] Analyzing image:
[validate : get-package-versions]     Python:     3.8.8
[validate : get-package-versions]     Packages:   argon2-cffi-bindings==21.2.0 awscli==1.21.12 elyra==2.2.4 farm==0.5.0 fuzzywuzzy==0.18.0 gdown==4.2.0 ipywidgets==7.6.5 jupyter-kernel-gateway==2.4.0 jupyter-nbrequirements==0.7.3 jupyterhub==1.3.0 jupyterlab-requirements==0.14.0 jupyterlab-spellchecker==0.7.2 mmcv-full==1.3.16 mmdet==2.18.0 mod-wsgi==4.6.8 opencv-python-headless==4.5.4.58 openpyxl==3.0.9 optuna==2.10.0 pdf2image==1.16.0 pdfminer.six==20211012 pipenv==2020.11.15 pyarrow==6.0.0 pydocstyle==6.1.1 pylint==2.12.1 PySocks==1.7.1 pyspellchecker==0.6.2 python-Levenshtein==0.12.2 rope==0.22.0 spacy==3.2.0 src==0.1.0 supervisor==4.1.0 tabula-py==2.3.0 torchvision==0.7.0 trino==0.306.0 xlrd==2.0.1

[validate : minimal-requirements] Validating minimal requirements:
[validate : minimal-requirements]     Python >= 3.8.0 ✅
[validate : minimal-requirements]     'jupyterhub' package is present ✅
[validate : minimal-requirements]     'jupyterlab' package is present ✅
[validate : minimal-requirements]     $HOME is writeable ✅
[validate : minimal-requirements]     start-singleuser.sh is present  ✅
[validate : minimal-requirements]     start-singleuser.sh must execute 'jupyter'  ✅
[validate : minimal-requirements]     start-singleuser.sh must start 'labhub' environment  ✅
[validate : minimal-requirements]     start-singleuser.sh must accept runtime args or pass a config file  ✅

[update-imagestream : oc] Updating image stream:
[update-imagestream : oc]   Name:       byon-import-jupyterhub-image-run-72f6n
[update-imagestream : oc]   Namespace:  byon
[update-imagestream : oc] 
[update-imagestream : oc]   Image tag:           latest
[update-imagestream : oc]   Phase:               Succeeded
[update-imagestream : oc]   Message:             
[update-imagestream : oc]   Visibility:          true
[update-imagestream : oc]   Software:            [{"name":"Python","version":"3.8.8"}]
[update-imagestream : oc]   Python dependencies: [{"name": "argon2-cffi-bindings", "version": "21.2.0"}, {"name": "awscli", "version": "1.21.12"}, {"name": "elyra", "version": "2.2.4"}, {"name": "farm", "version": "0.5.0"}, {"name": "fuzzywuzzy", "version": "0.18.0"}, {"name": "gdown", "version": "4.2.0"}, {"name": "ipywidgets", "version": "7.6.5"}, {"name": "jupyter-kernel-gateway", "version": "2.4.0"}, {"name": "jupyter-nbrequirements", "version": "0.7.3"}, {"name": "jupyterhub", "version": "1.3.0"}, {"name": "jupyterlab-requirements", "version": "0.14.0"}, {"name": "jupyterlab-spellchecker", "version": "0.7.2"}, {"name": "mmcv-full", "version": "1.3.16"}, {"name": "mmdet", "version": "2.18.0"}, {"name": "mod-wsgi", "version": "4.6.8"}, {"name": "opencv-python-headless", "version": "4.5.4.58"}, {"name": "openpyxl", "version": "3.0.9"}, {"name": "optuna", "version": "2.10.0"}, {"name": "pdf2image", "version": "1.16.0"}, {"name": "pdfminer.six", "version": "20211012"}, {"name": "pipenv", "version": "2020.11.15"}, {"name": "pyarrow", "version": "6.0.0"}, {"name": "pydocstyle", "version": "6.1.1"}, {"name": "pylint", "version": "2.12.1"}, {"name": "PySocks", "version": "1.7.1"}, {"name": "pyspellchecker", "version": "0.6.2"}, {"name": "python-Levenshtein", "version": "0.12.2"}, {"name": "rope", "version": "0.22.0"}, {"name": "spacy", "version": "3.2.0"}, {"name": "src", "version": "0.1.0"}, {"name": "supervisor", "version": "4.1.0"}, {"name": "tabula-py", "version": "2.3.0"}, {"name": "torchvision", "version": "0.7.0"}, {"name": "trino", "version": "0.306.0"}, {"name": "xlrd", "version": "2.0.1"}]
[update-imagestream : oc] 
[update-imagestream : oc] imagestream.image.openshift.io/byon-import-jupyterhub-image-run-72f6n patched
```
</details>

**Comment by codificat** [comment]
/unassign
/assign @tumido 
to /approve

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
